### ISSUE TITLE
The plugins file is missing or invalid.

### ISSUE THREAD

**Issue by bemarte** [dan-cooke/cypress-autostub#14]
When inserting the code below into the cypress/plugins/index.js, I am notified of an error in the plugins/index.js file and I can't run any test.

Cypress package version: 4.12.1
Cypress binary version: 4.12.1

```
// Import the plugin
import { autoStubSetup } from 'cypress-autostub'

module.exports = (on, config) => {

  autoStubSetup(on, {
      mockFileDirectory: 'cypress/fixtures'
  })
}
```

-

**Message:** The plugins file is missing or invalid.

Your `pluginsFile` is set to `/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
```
**Details:** cypress/plugins/index.js:15
import { autoStubSetup } from 'cypress-autostub'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:896:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at module.exports (/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js:208:15)
    at Object.<anonymous> (/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/lib/plugins/child/index.js:6:25)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
```
**Stack trace:**
```
Error: The plugins file is missing or invalid.

Your `pluginsFile` is set to `/cypress/plugins/index.js`, but either the file is missing, it contains a syntax error, or threw an error when required. The `pluginsFile` must be a `.js`, `.ts`, or `.coffee` file.

Or you might have renamed the extension of your `pluginsFile`. If that's the case, restart the test runner.

Please fix this, or set `pluginsFile` to `false` if a plugins file is not necessary for your project.
    at Object.get (/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/lib/errors.js:946:15)
    at EventEmitter.<anonymous> (/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/lib/plugins/index.js:123:21)
    at EventEmitter.emit (events.js:210:5)
    at ChildProcess.<anonymous> (/.cache/Cypress/4.12.1/Cypress/resources/app/packages/server/lib/plugins/util.js:19:22)
    at ChildProcess.emit (events.js:210:5)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

```

**Comment by dan-cooke** [comment]
You cannot use ‘import’ unless :
- you have setup ESModules in your package.json, 
- you are transpiling your code
- you are using typescript


Examples in this repo assume your cypress code is using typescript, this includes the plugins file.

closing as not related to cypress-autostub
